/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportForm.java
 *
 * Created on 21-Feb-2014, 18:45:26
 */
package pat;

import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.*;
import java.util.*;
import java.awt.Color.*;
import java.awt.*;


public class ReportForm extends MainExtensibleClass {

    /** Creates new form ReportForm */
    public ReportForm() {
        initComponents();
        this.getConnection();
        this.refreshLists();
    }

    public ReportForm(MainMenuForm caller) {
        initComponents();
        this.getConnection();
        this.parent = caller;
        this.refreshLists();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPresid = new javax.swing.JList();
        btnShowDetailPres = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstGovern = new javax.swing.JList();
        btnShowDetailGover = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSen = new javax.swing.JList();
        btnShowDetailSen = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstCouns = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstRep = new javax.swing.JList();
        btnShowDetailRep = new javax.swing.JButton();
        btnReferesh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Presidential"));

        jScrollPane1.setViewportView(lstPresid);

        btnShowDetailPres.setText("Show Chart");
        btnShowDetailPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDetailPresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowDetailPres))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowDetailPres))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Governorship"));

        jScrollPane2.setViewportView(lstGovern);

        btnShowDetailGover.setText("Show Chart");
        btnShowDetailGover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDetailGoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnShowDetailGover)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowDetailGover))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Senatorial"));

        jScrollPane3.setViewportView(lstSen);

        btnShowDetailSen.setText("Show Chart");
        btnShowDetailSen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDetailSenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowDetailSen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowDetailSen))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Counsellorship"));

        jScrollPane4.setViewportView(lstCouns);

        jButton3.setText("Show Chart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Representative"));

        jScrollPane5.setViewportView(lstRep);

        btnShowDetailRep.setText("Show Chart");
        btnShowDetailRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDetailRepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowDetailRep))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowDetailRep))
        );

        btnReferesh.setText("Refresh");
        btnReferesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefereshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClose)
                            .addComponent(btnReferesh))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnReferesh)
                        .addGap(24, 24, 24)
                        .addComponent(btnClose)
                        .addGap(94, 94, 94))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.hide();
        this.parent.show();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRefereshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefereshActionPerformed
        // TODO add your handling code here:
        this.refreshLists();
    }//GEN-LAST:event_btnRefereshActionPerformed

    private void btnShowDetailPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDetailPresActionPerformed
        // TODO add your handling code here:
        this.drawChart(1);
    }//GEN-LAST:event_btnShowDetailPresActionPerformed

    private void btnShowDetailGoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDetailGoverActionPerformed
        // TODO add your handling code here:
        this.drawChart(2);
    }//GEN-LAST:event_btnShowDetailGoverActionPerformed

    private void btnShowDetailSenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDetailSenActionPerformed
        // TODO add your handling code here:
        this.drawChart(3);
    }//GEN-LAST:event_btnShowDetailSenActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.drawChart(4);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnShowDetailRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDetailRepActionPerformed
        // TODO add your handling code here:
        this.drawChart(5);
    }//GEN-LAST:event_btnShowDetailRepActionPerformed

    private void clearLists() {
        DefaultListModel listModel = new DefaultListModel(); //lstCouns.getModel();
        //listModel.removeAllElements();
        this.lstCouns.setModel(listModel);
        DefaultListModel listModel2 = new DefaultListModel();
        //listModel.removeAllElements();
        this.lstGovern.setModel(listModel2);
        DefaultListModel listModel3 = new DefaultListModel();
        //listModel.removeAllElements();
        this.lstPresid.setModel(listModel3);
        DefaultListModel listModel4 = new DefaultListModel();
        //listModel.removeAllElements();
        this.lstRep.setModel(listModel4);
        DefaultListModel listModel5 = new DefaultListModel();
        //listModel.removeAllElements();
        this.lstSen.setModel(listModel5);
    }

    private void refreshLists() {
        this.clearLists();
        //lets get presidential vote counts
        String qry1 = "select * from tbl_voting_setup where category_id = '1' and status = '1'";
        ResultSet tempPresid = this.dbConnection.fetchrows(qry1);
        String qry2 = "select * from tbl_voting_setup where category_id = '2' and status = '1'";
        ResultSet tempGovern = this.dbConnection.fetchrows(qry2);
        String qry3 = "select * from tbl_voting_setup where category_id = '3' and status = '1'";
        ResultSet tempSenat = this.dbConnection.fetchrows(qry3);
        String qry4 = "select * from tbl_voting_setup where category_id = '4' and status = '1'";
        ResultSet tempCouns = this.dbConnection.fetchrows(qry4);
        String qry5 = "select * from tbl_voting_setup where category_id = '5' and status = '1'";
        ResultSet tempRep = this.dbConnection.fetchrows(qry5);

        //lets load presidential result
        this.loadResultToList(tempPresid, this.lstPresid);

        //lets load governorship result
        this.loadResultToList(tempGovern, this.lstGovern);

        //lets load senatorial result
        this.loadResultToList(tempSenat, this.lstSen);

        //lets load counsellorship result
        this.loadResultToList(tempCouns, this.lstCouns);

        //lets load representative result
        this.loadResultToList(tempRep, this.lstRep);

    }

    private void drawChart(int arg) {
        ArrayList<ListPairItem<Double>> values = new ArrayList<ListPairItem<Double>>();
        ResultSet tempRS = null;
        switch (arg) {
            case 1:
                String qry1 = "select * from tbl_voting_setup where category_id = '1' and status = '1'";
                tempRS = this.dbConnection.fetchrows(qry1);
                break;
            case 2:
                String qry2 = "select * from tbl_voting_setup where category_id = '2' and status = '1'";
                tempRS = this.dbConnection.fetchrows(qry2);
                break;
            case 3:
                String qry3 = "select * from tbl_voting_setup where category_id = '3' and status = '1'";
                tempRS = this.dbConnection.fetchrows(qry3);
                break;
            case 4:
                String qry4 = "select * from tbl_voting_setup where category_id = '4' and status = '1'";
                tempRS = this.dbConnection.fetchrows(qry4);
                break;
            case 5:
                String qry5 = "select * from tbl_voting_setup where category_id = '5' and status = '1'";
                tempRS = this.dbConnection.fetchrows(qry5);
                break;
        }

        int totalCount = 0;
        if (tempRS != null) {
            try {
                while (tempRS.next()) {
                    String candidate_id = tempRS.getString("candidate_id");
                    ResultSet tempCandidates = this.dbConnection.fetchrows("select "
                            //+ "B.*,"
                            + "A.fname,A.lname,A.title,A.group_id "
                            //+ ", C.group_id "
                            + "from tbl_candidate as A "
                            //+ " left join tbl_voting as B on (Cint(A.choice) = B.ID)"
                            //+ " left join tbl_group as C on (Cint(B.group_id) = C.ID) "
                            //+ "left outer join tbl_voting as D ON (A.ID = D.ID) "
                            + "where (A.ID = Cint('" + candidate_id + "'))");
                    //+ "";
                    String voteCount = "0";
                    if (tempCandidates.next()) {
                        ResultSet tempVote = null;
                        try {
                            tempVote = this.dbConnection.fetchrows("select count(*) as number_of_vote "
                                    + "from tbl_voting "
                                    + "where (choice = '" + candidate_id + "')");
                            tempVote.next();
                            voteCount = tempVote.getString("number_of_vote");
                        } catch (Exception ee) {
                        }


                        ResultSet tempGroup = this.dbConnection.fetchrows("select * "
                                + "from tbl_group "
                                + "where (ID = Cint('" + tempCandidates.getString("group_id") + "'))");
                        tempGroup.next();

                        String temp = tempCandidates.getString("fname") + " "
                                + "" + tempCandidates.getString("lname")
                                + " (" + tempGroup.getString("group_name") + ") "
                                + " " + voteCount;
                        totalCount +=Double.parseDouble(voteCount);
                        values.add(new ListPairItem(temp,Double.parseDouble(voteCount)));
                    }
                    
                }
            } catch (Exception ex) {
                System.err.println(ex.toString());
            }
            drawChart(values,totalCount);
        }

    }

    private void loadResultToList(ResultSet tempRS, javax.swing.JList lstBox) {
        //lets load results
        try {
            while (tempRS.next()) {
                String candidate_id = tempRS.getString("candidate_id");
                ResultSet tempCandidates = this.dbConnection.fetchrows("select "
                        //+ "B.*,"
                        + "A.fname,A.lname,A.title,A.group_id "
                        //+ ", C.group_id "
                        + "from tbl_candidate as A "
                        //+ " left join tbl_voting as B on (Cint(A.choice) = B.ID)"
                        //+ " left join tbl_group as C on (Cint(B.group_id) = C.ID) "
                        //+ "left outer join tbl_voting as D ON (A.ID = D.ID) "
                        + "where (A.ID = Cint('" + candidate_id + "'))");
                //+ "";
                String voteCount = "0";
                if (tempCandidates.next()) {
                    ResultSet tempVote = null;
                    try {
                        tempVote = this.dbConnection.fetchrows("select count(*) as number_of_vote "
                                + "from tbl_voting "
                                + "where (choice = '" + candidate_id + "')");
                        tempVote.next();
                        voteCount = tempVote.getString("number_of_vote");
                    } catch (Exception ee) {
                    }


                    ResultSet tempGroup = this.dbConnection.fetchrows("select * "
                            + "from tbl_group "
                            + "where (ID = Cint('" + tempCandidates.getString("group_id") + "'))");
                    tempGroup.next();

                    String temp = tempCandidates.getString("fname") + " "
                            + "" + tempCandidates.getString("lname")
                            + " (" + tempGroup.getString("group_name") + ") "
                            + " " + voteCount;
                    DefaultListModel listModel = (DefaultListModel) lstBox.getModel();
                    listModel.addElement(temp);
                    lstBox.setModel(listModel);
                }
            }
        } catch (Exception ex) {
            System.err.println(ex.toString());
        }
    }

    public static void drawChart(ArrayList<ListPairItem<Double>> valuesArg,int actualTotal) {


        ArrayList<Color> colors = new ArrayList<Color>();
        ArrayList<Double> values = new ArrayList<Double>();
        JFrame frame = new JFrame();
        JPanel pieChartPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        //pieChartPanel.setLayout(new GridLayout(4, 1, 0, 5));
        //pieChartPanel.setLayout(new GridLayout(4, 1, 0, 5));
        pieChartPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 5, 20));

        JPanel bottom = new JPanel(new FlowLayout(FlowLayout.TRAILING));
        bottom.setBorder(BorderFactory.createEmptyBorder(5, 20, 5, 20));

        //frame.doLayout();
        int total = 100;
        for (int i = 0; i < valuesArg.size(); i++) {
            ListPairItem<Double> temp = valuesArg.get(i);
            Double tempV = (temp.getItem()/actualTotal) * total;
            values.add(tempV);
            //total += tempV;
            Color tempC = new Color(pieChart.randInt(0, 255), pieChart.randInt(0, 255), pieChart.randInt(0, 255));
            colors.add(tempC);
            System.out.println("Value: " + tempV + " " + tempC);
            JLabel tempL = new JLabel(temp.toString() + ": " + tempV);
            tempL.setBackground(tempC);
            tempL.setForeground(tempC);
            tempL.setSize(10, 6);
            tempL.setVisible(true);
            //tempL.
            bottom.add(tempL);
        }



        //int  grade = 100;
        pieChart pc = new pieChart(total, values, colors);

        pc.setVisible(true);
        //pc.setLayout(new GridLayout(4, 1, 0, 5));
        pc.setBorder(BorderFactory.createEmptyBorder(300, 300, 200, 200));
        pc.setSize(300, 300);

        //pieChartPanel.add(pc);
        //pieChartPanel.setVisible(true);
        frame.setLayout(new BorderLayout());
        frame.add(pc, BorderLayout.PAGE_START);
        frame.add(bottom, BorderLayout.PAGE_END);
        //frame.setSize((int)(frame.getSize().width*1.6), frame.getSize().height);
        //frame.setLocationRelativeTo(null);
        //frame.setTemplate(null);
        //frame.getContentPane().add(pieChartPanel);
        frame.pack();
        frame.setSize(800, 600);
        frame.setVisible(true);
    }
    /**
     * @param args the command line arguments
    
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
    new ReportForm().setVisible(true);
    }
    });
    }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReferesh;
    private javax.swing.JButton btnShowDetailGover;
    private javax.swing.JButton btnShowDetailPres;
    private javax.swing.JButton btnShowDetailRep;
    private javax.swing.JButton btnShowDetailSen;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList lstCouns;
    private javax.swing.JList lstGovern;
    private javax.swing.JList lstPresid;
    private javax.swing.JList lstRep;
    private javax.swing.JList lstSen;
    // End of variables declaration//GEN-END:variables
}
