/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VotersRegistrationForm.java
 *
 * Created on 10-Feb-2014, 17:26:15
 */

package pat;

import com.digitalpersona.onetouch.DPFPTemplate;
import java.util.*;
import javax.swing.JLabel;


public class VotersRegistrationForm extends MainExtensibleClass {

    private int currentFingerSelection = 0;
    private DPFPTemplate leftTemplate;
    private DPFPTemplate rightTemplate;
    
    /** Creates new form VotersRegistrationForm */
    public VotersRegistrationForm() {
        initComponents();
        this.getConnection();
    }


    public VotersRegistrationForm(MainMenuForm parentObj) {
        this.parent = parentObj;
        initComponents();
        this.getConnection();
    }

    public void setFingerCapturedTemplate(DPFPTemplate template,JLabel actualImage)
    {

        switch(this.currentFingerSelection)
        {
            case 1:
                this.leftTemplate = template;
                this.lblThumbLeft.setIcon(actualImage.getIcon());
                //picture.setIcon(new ImageIcon(
		//	image.getScaledInstance(picture.getWidth(), picture.getHeight(), Image.SCALE_DEFAULT)));
                break;
            case 2:
                this.rightTemplate = template;
                this.lblThumbRight.setIcon(actualImage.getIcon());
                break;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboMarritalstatus = new javax.swing.JComboBox();
        txtSurname = new javax.swing.JTextField();
        txtOthername = new javax.swing.JTextField();
        cboTitle = new javax.swing.JComboBox();
        txtFirstname = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtAddress3 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblThumbLeft = new javax.swing.JLabel();
        lblThumbRight = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboMarritalstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married" }));

        cboTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr", "Dr.", "Mrs", "Dr. Mrs", "Barrister", "Col.", "Lt.", "Gen.", "Brig.", "Brig. Gen." }));

        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel12.setText("Country:");

        jLabel10.setText("City:");

        jLabel11.setText("Phone number:");

        jLabel13.setText("Email:");

        jLabel14.setText("Finger Print Registration:");

        jLabel2.setText("Select Title:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Voters Registration");

        jLabel9.setText("Address Line 3:");

        jLabel6.setText("Marrital Status:");

        jLabel5.setText("Enter Voters Othername:");

        jLabel4.setText("Enter Voters Lastname:");

        jLabel3.setText("Enter Voters Firstname:");

        jLabel8.setText("Address Line 2:");

        jLabel7.setText("Address Line 1:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Click on finger print window to capture fingerprint"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThumbLeft.setBorder(javax.swing.BorderFactory.createTitledBorder("Thumb Left"));
        lblThumbLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThumbLeftMouseClicked(evt);
            }
        });
        jPanel1.add(lblThumbLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 280));

        lblThumbRight.setBorder(javax.swing.BorderFactory.createTitledBorder("Thumb Right"));
        lblThumbRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThumbRightMouseClicked(evt);
            }
        });
        jPanel1.add(lblThumbRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 230, 280));

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel1)
                .addContainerGap(557, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboMarritalstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstname, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(txtSurname)
                                    .addComponent(txtOthername)
                                    .addComponent(txtAddress1)
                                    .addComponent(txtAddress2)
                                    .addComponent(txtAddress3))))
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(btnSave)
                .addGap(31, 31, 31)
                .addComponent(btnClose)
                .addContainerGap(520, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtOthername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboMarritalstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblThumbLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThumbLeftMouseClicked
        // TODO add your handling code here:
        if(true)
        {
            EnrollmentForm form = new EnrollmentForm(this);
            this.currentFingerSelection = 1;
            form.setVisible(true);
        }
    }//GEN-LAST:event_lblThumbLeftMouseClicked

    private void lblThumbRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThumbRightMouseClicked
        // TODO add your handling code here:
        if(true)
        {
            EnrollmentForm form = new EnrollmentForm(this);
            this.currentFingerSelection = 2;
            form.setVisible(true);
        }
    }//GEN-LAST:event_lblThumbRightMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ArrayList <ListPairItem> arrData = new ArrayList <ListPairItem> ();

        //try{this.dbConnection.getTemplateFromDatabase(13, "finger_template2");}catch(Exception ex){}

        if(this.leftTemplate==null || this.rightTemplate==null)
        {
            new Alert("Invalid Finger Print Template");
            return;
        }
        
        try{
            //lets collate all informatioon supplied for candidate
            arrData.add(new ListPairItem ("fname",this.txtFirstname.getText()));
            arrData.add(new ListPairItem ("lname",this.txtSurname.getText()));
            arrData.add(new ListPairItem ("oname",this.txtOthername.getText()));
            arrData.add(new ListPairItem ("marrital_status",this.cboMarritalstatus.getSelectedItem().toString()));
            arrData.add(new ListPairItem ("address1",this.txtAddress1.getText()));
            arrData.add(new ListPairItem ("address2",this.txtAddress2.getText()));
            arrData.add(new ListPairItem ("address3",this.txtAddress3.getText()));
            arrData.add(new ListPairItem ("city",this.txtCity.getText()));
            arrData.add(new ListPairItem ("country",this.txtCountry.getText()));
            arrData.add(new ListPairItem ("phone_number",this.txtPhone.getText()));
            arrData.add(new ListPairItem ("email",this.txtEmail.getText()));
            arrData.add(new ListPairItem ("title",this.cboTitle.getSelectedItem().toString()));
            arrData.add(new ListPairItem ("creation_date",java.util.Calendar.getInstance(Locale.ENGLISH).toString()));


            //lets add the information to the database
            this.dbConnection.insertData(arrData, "tbl_voters");
            int id = this.dbConnection.get_Last_Inserted_ID("tbl_voters");
            //lets add the finger print template
            this.dbConnection.addTemplateToDatabase(id,this.leftTemplate,"finger_template1");
            this.dbConnection.addTemplateToDatabase(id,this.rightTemplate,"finger_template2");
            
            DPFPTemplate tempTemplate = this.dbConnection.getTemplateFromDatabase(id, "finger_template1");
            
            this.clearFormFields();
            new Alert("Voter Registered Successfully");
        }
        catch(Exception ex){
            System.out.println(ex.toString());
            ex.printStackTrace();
            new Alert("Error occured:"+ex.toString());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.hide();
        this.parent.show();
}//GEN-LAST:event_btnCloseActionPerformed

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed


    private void clearFormFields()
    {
        this.txtFirstname.setText("");
        this.txtSurname.setText("");
        this.txtOthername.setText("");
        this.cboMarritalstatus.setSelectedIndex(0);
        this.txtAddress1.setText("");
        this.txtAddress2.setText("");
        this.txtAddress3.setText("");
        this.txtCity.setText("");
        this.txtCountry.setText("");
        this.txtPhone.setText("");
        this.txtEmail.setText("");
        this.cboTitle.setSelectedIndex(0);

        this.leftTemplate = null;
        this.rightTemplate = null;
    }
    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotersRegistrationForm().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cboMarritalstatus;
    private javax.swing.JComboBox cboTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblThumbLeft;
    private javax.swing.JLabel lblThumbRight;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtAddress3;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtOthername;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

}
