/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VotingForm.java
 *
 * Created on 10-Feb-2014, 17:23:49
 */

package pat;


public class VotingForm extends MainExtensibleClass {

    private int voterId;
    private String votersName;

    /** Creates new form VotingForm */
    public VotingForm() {
        initComponents();
    }


    public VotingForm(MainMenuForm parentObj) {
        this.parent = parentObj;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerify = new javax.swing.JButton();
        btnCastVote = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVerify.setText("Verify");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        btnCastVote.setText("Cast Vote");
        btnCastVote.setEnabled(false);
        btnCastVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCastVoteActionPerformed(evt);
            }
        });

        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo.setText("Please Click on Verify to proceed.");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnVerify))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnCastVote)))
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(btnClose)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblInfo)
                .addGap(18, 18, 18)
                .addComponent(btnVerify)
                .addGap(18, 18, 18)
                .addComponent(btnCastVote)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:
        VerificationForm veriForm = new VerificationForm(this);
        veriForm.setVisible(true);
        //this.hide();

}//GEN-LAST:event_btnVerifyActionPerformed

    private void btnCastVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCastVoteActionPerformed
        // TODO add your handling code here:
       CastVoteForm form = new CastVoteForm(this);
       form.show();
       this.hide();
       this.setEnableVote(false);
    }//GEN-LAST:event_btnCastVoteActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.hide();
        this.parent.show();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void setInfoLabel()
    {
        this.lblInfo.setText("Welcome, "+this.votersName+" Please proceed by Clicking on cast vote.");
    }

    private void restoreInfoLabel()
    {
        this.lblInfo.setText("Please Click on Verify to proceed.");
    }

    public void setEnableVote(boolean val)
    {
        if(val)
        {
            this.setInfoLabel();
        }
        else
        {
            this.restoreInfoLabel();
        }
        
        this.btnCastVote.setEnabled(val);
    }

    public void setVoterDetail(int val,String voterName )
    {
        this.votersName = (voterName==null)?"":voterName;
        this.voterId = val;
    }

    public void setVoterDetail(int val )
    {
        this.voterId = val;
    }

    public int getVoterId()
    {
        return  this.voterId;
    }

    public String getVoterName()
    {
        return  this.votersName;
    }
    /**
    * @param args the command line arguments
   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotingForm().setVisible(true);
            }
        });
    }
 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCastVote;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables

}
